---
title: "toolik_chem"
format: html
---

```{r}
library(tidyverse)
library(here)
library(janitor)
library(purrr)
```

```{r}
#loading in my data and clean it
toolik_biochem <- read_csv(here::here("data", "2011_Kling_Akchem.csv")) %>% 
  janitor::clean_names() %>% 
  mutate(across(where(is.character), ~na_if(., ".")))
```
```{r}
inlet_biochem <- toolik_biochem %>% 
  dplyr::filter(site == "Toolik Inlet") %>% 
  dplyr::select(p_h, doc_u_m, tdn_u_m) 

inlet_biochem$p_h <- as.numeric(inlet_biochem$p_h)
inlet_biochem$doc_u_m <- as.numeric(inlet_biochem$doc_u_m)
inlet_biochem$tdn_u_m <- as.numeric(inlet_biochem$tdn_u_m)
```

```{r}
apply(X = inlet_biochem, MARGIN = 2, FUN = mean, na.rm = TRUE)
```

```{r}
mean(inlet_biochem$p_h, na.rm = TRUE)
mean(inlet_biochem$doc_u_m, na.rm = TRUE)
mean(inlet_biochem$tdn_u_m, na.rm = TRUE)
```



```{r}
mean_inlet <- vector(mode = "numeric", length = ncol(inlet_biochem))

for(i in 1:ncol(inlet_biochem)){
  mean_inlet[i] <- mean(inlet_biochem[[i]], na.rm = TRUE)
}

print(mean_inlet)

```

```{r}
map_df(.x = inlet_biochem, .f = mean, na.rm = TRUE)
```

